### ISSUE TITLE
segments missing if system language is not English

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [gnoling/UnlinkMKV#9] opened 2015-12-21 14:32 UTC
If system language is not English, segment analysis will fail because of mkvinfo chosing the corresponding locale

**Comment by ghost** [comment] 2015-12-21 21:58
Interesting issue. So I assume the problem is that it misses _English_ subtitles in this case? Or rather, it'll only work if the subtitles in question match the in-use locale.

If that's the case, the correct fix sounds like a forced default locale in the script + an option to specify a different locale/override that behaviour.

**Comment by sPaCeMoNk3yIam** [comment] 2015-12-21 22:50
No, like I said, it's a problem with mkvinfo. In my case the system language is German, so mkvinfo is displaying the infos in German, too. But your script seems to look for the output of mkvinfo in English, doesn't find what it's looking for and therefor displays "segments missing".

**Comment by hilts-vaughan** [comment] 2016-05-18 00:59
This can be fixed by over-writing `LANG`.

**Comment by siferati** [comment] 2017-08-24 13:30
As a note, instead of changing your system language, you can just delete your language folder from mkvtoolnix/locale.

Mkvinfo will default to english if there's no locale for your system language.

**Closed as completed** 2017-08-24 14:43 UTC
