### ISSUE TITLE
UnlinkMKV doesn't work with my pc.

### ISSUE THREAD

**Issue by mohitmallick17** [gnoling/UnlinkMKV#20] opened 2017-01-23 18:00 UTC
Hi I am using windows 10 with all the tools like mediainfo , mkvtoolnix , ffmpeg , strawberryperl installed on my pc. The problem is that whenever I click on the unlinkMkV.exe the command prompt like black window appears but in less than two seconds it closes and it never opens. I've downloaded the latest version of unlinkmkv and other tools and tries older versions too but nothing helps me. I get the same problem of opening cmd for few seconds and then closing but the program never opens. I've tried running with different compaliblity but it gives the same problem.
Please help me as I can't find a single other program to do this job and I have bulk of things to do.

**Comment by gnoling** [comment] 2017-01-23 18:01
UnlinkMKV is a console, not a GUI, application. It closes right away because it has nothing to do.

There are instructions for using it in the readme

**Comment by mohitmallick17** [comment] 2017-01-23 18:07
So how exactly am I supposed to use it then ? I've read the instructions and I guess that the .exe program should open it. Atleast it shouldn't close as soon as we launch it. How can I use it ?

**Comment by gnoling** [comment] 2017-01-23 18:24
Again, this is a command line application, which means you have to use it from a command prompt. You control it by passing parameters to it from the command prompt.

- Extract it somewhere, like c:\unlinkmkv
- Open a command prompt (Google it for Windows 10), or, go to the folder of your anime, right click not on a file, and select "Open Command Prompt Here"
- If your command prompt is already in the correct directory (the path should show in the prompt), unlinkmkv will try and process all files in that working directory, and to launch it from the earlier suggested extracted path you would (note the period -- a period means "this", or the current directory):
`c:\unlinkmkv\unlinkmkv .`

The default options work for most files, so hopefully that should do the trick for you. Instead of a period or being in the correct directory, you can also pass filenames to it.

**Comment by mohitmallick17** [comment] 2017-01-23 18:33
I've understood the first two points but the last one is unclear to me. After I go to the folder and right click, then open command line there.. I didn't get after that...I mean this statement of yours


If your command prompt is already in the correct directory (the path should show in the prompt), unlinkmkv will try and process all files in that working directory, and to launch it from the earlier suggested extracted path you would (note the period -- a period means "this", or the current directory):
c:\unlinkmkv\unlinkmkv .


Btw I am really happy that you helped me. Thanks a bunch just let me know what you meant by the last point

**Comment by mohitmallick17** [comment] 2017-01-23 18:45
Dear do you mean that on right clicking and selecting open command line here, cmd will appear. After that the path of the directory will be shown on command prompt. What should I type next to merge my stuffs ? Readme didn't helo me so I am asking it here

**Comment by gnoling** [comment] 2017-01-23 18:47
If you extracted unlinkmkv to c:\unlinkmkv, type this:

**c:\unlinkmkv\unlinkmkv .**

And press enter. It should try and find any mkv files that are segmented and process them with default options.

**Comment by gnoling** [comment] 2017-01-23 18:48
Correction, it should try and find any in the directory you're currently in. So if you open the command prompt as I described in the directory with your anime (not the one with unlinkmkv), it should work.

**Comment by mohitmallick17** [comment] 2017-01-23 18:58
I see. Means I'll just have to type the directory of the program. Thanks a bunch man.
I'll close this issue as soon as I test and it work for me(probably tomorrow noon) 
Can it merge hi10p animes properly. Last time an application couldn't merge it properly and the op/ed got corrupted.
I also wanna know that besides default, what all other options I've got and how can I use them..

**Comment by mohitmallick17** [comment] 2017-01-23 19:08
unlinkmkv --fixaudio --fixvideo --outdir "/home/user/Desktop/Princess Ressurection" princess-ressurection-ep-1.mkv

Like --outdir here.
I've one more question. If I don't wanna go to the anine directory but I'll simply open cmd from start menu or run then what sh'd be the steps.. Is it possible ?

**Comment by gnoling** [comment] 2017-01-23 19:22
Yeah, unlinkmkv either takes a file or a directory as for what to process. It's easier to browse to the directory in your file manager first, right click WHILE HOLDING THE SHIFT key in the window, and clicking open command prompt here. That just opens the command prompt already changed to the directory you were looking at. Then from there you invoke unlinkmkv specifying a period as the input, which is literally the same as specifying the full directory you're currently in. When given a directory like that, it'll just try and process all files in that directory.

Outdir is optional, you don't actually have to specify it. It'll just end up in a sub directory of your current directory. It looks weird in the example because thats how you format them in Linux, in windows you'd do it like "C:\My\Output\Directory".

As far as hi10p goes, it entirely depends on how whoever encoded them did so. If they were made exactly the same, they'll usually show fine afterwards -- unfortunately some don't. In those cases you can almost always fix it by adding --fixvideo, which actually re-encodes the video to something that can be appended fine. Be mindful that the result will be 8-bit, and slightly larger then the source files. Fix audio does the same thing but for audio streams.

Also, at some point I renamed --fix-video to --fixvideo. I'm honestly not sure if that was before or after the last time I updated the exe, so its actually possible you'll need to try both.

**Comment by mohitmallick17** [comment] 2017-01-23 19:45
That's a great help. Thanks a lot bro. I think I've got enough theoretical knowledge on this topic. Rest is upto me how I perform the task. If I get stuck anywhere on the practical thing I'll let you know. Thanks a lot again. I really am grateful to you for this help

**Comment by mohitmallick17** [comment] 2017-01-24 09:42
![screenshot 121](https://cloud.githubusercontent.com/assets/22490775/22241906/5c1e6414-e247-11e6-8370-9e67feb6be66.png)
![screenshot 122](https://cloud.githubusercontent.com/assets/22490775/22241915/6cc19714-e247-11e6-984f-08650c0890c2.png)
![screenshot 123](https://cloud.githubusercontent.com/assets/22490775/22241939/79e38cd6-e247-11e6-9153-97c673335eee.png)

**Comment by mohitmallick17** [comment] 2017-01-24 09:45
This is where I am stuck. I've opened cmd and I've put the unlinkMKV directory and all the process was done in an instant. As soon as I pressed enter everything got done and nothing was available on output folder I've sent a screenshot.. Maybe I went wrong somewhere. What should I do ? Please help me

**Comment by mohitmallick17** [comment] 2017-01-24 10:04
Sorry I think I went wrong here. Maybe I sh'd have specified the filename as well.
I did that too (I'll send the new screenshots)  but after the processing is done nothing is on output folder. Where did I go wrong ?

**Comment by mohitmallick17** [comment] 2017-01-24 10:05
![screenshot 124](https://cloud.githubusercontent.com/assets/22490775/22242770/a853fcce-e24a-11e6-9696-9d40fcdcc486.png)
![screenshot 125](https://cloud.githubusercontent.com/assets/22490775/22242785/b4038648-e24a-11e6-9e7f-dbfa4c762635.png)
![screenshot 126](https://cloud.githubusercontent.com/assets/22490775/22242810/c4e1030a-e24a-11e6-82f4-d094f0ebffe8.png)

**Comment by gnoling** [comment] 2017-01-24 15:32
In the first screenshot you were missing the period as an argument to tell it to use your current directory. Based on your later screenshots I'm guessing these files probably need **--ignoredefaultflag**.

I'd do the same thing you did there but adding --ignoredefaultflag, -ll TRACE, and --fix-video, so..

c:\unlinkmkv\unlinkmkv --ignoredefaultflag -ll TRACE --fix-video (Hi10)_...

"Ignore default flag" is a work around for when the chapters incorrectly set the default edition flag in the chapters, you can see in your output that it's dropping one of these. The "-ll TRACE" parameter will increase the log level to be far more verbose, and --fix-video will re-encode the video. I'd try one with and one without the --fix-video flag, probably without first, check that all the parts play properly, and if not try it with.

**Comment by mohitmallick17** [comment] 2017-01-24 16:56
I want to tell you that out of ten episodes only two were able to be merged. The rest of the files show the processing but later there's no output.(I've not checked --ignoredefaultflag but I'll do it tomorrow) 

Besides this all the episodes I've merged , even with --fixaudio and --fixvideo the OP and ED are getting corrupted. Is there any way to prevent this. (PS: I think that I've used --fixvideo instead of --fix-video so maybe it actually didn't get encoded to 8-bit ) anyways I want your assistance regading why  I can't merge all files but only some (once again I'll tell that --ignoredefaultflag isn't tested yet) and the OP ED  corruption.

**Comment by gnoling** [comment] 2017-01-24 16:58
From your screenshot earlier it does look like this binary was before I renamed the fix-video parameter, so it is going to need --fix-video to fix the video corruption issue. It's pretty likely --ignoredefaultflag will fix your other issue too. Let me know how it goes and/or close this issue if it resolves your problem.

**Comment by mohitmallick17** [comment] 2017-01-24 17:09
I surely will close this issue once my problem gets solved. All I have to do is check whether the arguements you've given me to fix the issues does work or not. So if evrything goes well I'll be done by tomorrow.
I wanted to ask of there's any difference between --fixvideo and --fix-video
And also the function of --ignoredefaultflag

**Comment by gnoling** [comment] 2017-01-24 18:21
fix-video and fixvideo are the same thing, I renamed it in newer versions of unlinkmkv but the dist archive still contains a slightly older version of unlinkmkv from before I renamed the option.

As for the ignoredefaultflag option, matroska files can have multiple "editions" (like angles in DVDs), and the default edition flag indicates which one plays by default. UnlinkMKV itself can't deal with alternate editions, so it will ignore ("drop") alternate editions when processing files. Unfortunately some releases don't set these flags quite properly (disabling the -only- edition, which in some players, just deal with this by playing it anyway since there are no alternates in the file); the --ignoredefaultflag changes UnlinkMKV's behavior and simply skips this sanity check and includes these segments anyway.

**Comment by mohitmallick17** [comment] 2017-01-25 13:49
I've included --ignoredefaultflag , --ll TRACE and --fix-video arguments but there's no change in the files. Same problem that most of the files bring empty folder (means no output) and the successful ones give corrupted OP ED ... if adding arguemens doesn't solve the problem then can you suggest me another solution ? I've tried most of the arguments I could find but nothing brought any change. Even 95% of videos process finishes without output and the remaining 5% gives corrupted chapters 
![screenshot 133](https://cloud.githubusercontent.com/assets/22490775/22292821/22673114-e333-11e6-815f-dd0dd67037fa.png)

**Comment by RTKurek** [comment] 2017-08-13 22:39
For what it's worth, I am having a very similar issue. I've managed to successfully unlink a few files, but most quietly fail and nothing appears in the output folder. I am using the compiled Windows version. 

Here's some output from running with the --ignoredefaultflag and --ll TRACE options on. It looks to me like the problem is happening right at the end: "sys < Error: No streams to output were found. Aborting." Not exactly sure what's causing this, though.

I'd appreciate any help you can offer!
[unlinkmkv-output.txt](https://github.com/gnoling/UnlinkMKV/files/1220985/unlinkmkv-output.txt)

**Comment by gnoling** [comment] 2017-08-15 18:37
Looks like theres an issue with the windows build detecting the ignore default option, try it with "--ignoredef".

**Closed as completed** 2017-08-21 19:27 UTC
