### ISSUE TITLE
file failed to build

### ISSUE THREAD

**Issue by alucryd** [gnoling/UnlinkMKV#37] opened 2020-04-17 20:44 UTC
Hi there, I'm having troubles trying to unlink some files, but even with DEBUG logging, I don't have much to work with: https://paste.xinu.at/gPUFFDXeeiU8Dn7c/

Would you be able to give some pointers as to what could go wrong, or how to get more info?

**Comment by gnoling** [comment] 2020-04-17 20:47
Sure. Can you please run it with TRACE level logging (**--loglevel trace**) and include that log?

**Comment by alucryd** [comment] 2020-04-18 04:21
Sure thing, there you go: https://paste.xinu.at/rr9amI6P7mgkhUJ1/

**Comment by gnoling** [comment] 2020-04-18 16:10
Looks like this is caused by these files having a FLAC track for audio, mkvmerge can't split that type of track. Unfortunately the fix audio flag that re-encodes the audio track was added for fixing files that couldn't be merged, so it was added after the portion that does splitting near the end of the process. I think if I move that before splitting instead that it'd resolve this (perhaps to another lossless format to prevent quality loss here?).

**Comment by alucryd** [comment] 2020-04-19 14:52
Oh I see. Yes another lossless format would be great, we could then go back to FLAC from that. What lossless formats can mkvmerge split?

**Comment by gnoling** [comment] 2020-04-20 15:17
Can you try this (Or just checkout from the feature/flac_workaround branch)?

https://raw.githubusercontent.com/gnoling/UnlinkMKV/feature/flac_workaround/unlinkmkv

In the above version I added a simple FLAC format check directly after where it verifies found segments, and converts them to ALAC with FFMPEG as needed; Then, at the end, it converts back to FLAC. Right now be mindful of the following notes with this test version:

- The ffmpeg settings for the ALAC/FLAC conversions are not yet configurable
- It does require more free space, since you'll have another working file w/ the converted audio
- Your ffmpeg does need to have FLAC+ALAC support built in

I actually had a test case for this locally already, which seems to build fine with this.

**Comment by alucryd** [comment] 2020-04-22 10:56
Thanks, it went further, but still failed in the end, here is the log: https://paste.xinu.at/5KBhCyXkI59w2RI3/

**Comment by gnoling** [comment] 2020-04-22 13:34
Whoops!

Looks like I forgot to actually push the commit... sorry about that. The version I had you try didn't contain the FLAC work-around. Would you mind trying once again? Same branch/file, this time with the actual changes.

**Comment by alucryd** [comment] 2020-04-22 16:02
Almost there! https://paste.xinu.at/cG61ZSSPWBZ7GSdH/

**Comment by gnoling** [comment] 2020-04-22 16:22
It looks like the OP and ED have soft subs, but the episodes don't?

Right now UnlinkMKV doesn't support a mixed number of tracks; If the subtitles aren't important, you could simply remux the NCOP/NCED without the subtitle tracks (doing this with the mkvtoolnix-gui would work fine, or the cli tools), making sure to move the originals out of the folder before using unlinkmkv later on. You'd probably want to also use --no-fixsubtitles as well for that use case.

**Comment by alucryd** [comment] 2020-04-22 17:02
Apologies, forgot to remove the subs from the OP and ED. Without subs it works like a charm, thanks a lot!

**Comment by gnoling** [comment] 2020-04-22 17:47
No prob

**Closed as completed by gnoling** 2020-04-22 17:47 UTC

**Comment by counterfit** [comment] 2020-04-23 02:35
Just worked for me, as well. (after I figured out my multitude of config problems. Lots of room for PEBCAK issues here.)
